### PR TITLE
Fix default method

### PR DESCRIPTION
**Pull request by michalk8**
This PR fixes an incorrect error type and the fact that the default method is set only once.

### CODE REVIEW

**Comment by Marius1311** [comment]
@msmdev , we had an issue with using GPCCA without SLEPSc - it worked the first time you called it, but not the second, see the linked issue on cellrank. This should fix the problem.

**Comment by Marius1311** [comment]
HI @msmdev , did you have time to look at this yet?

**Comment by msmdev** [comment]
@Marius1311 got to it just now...

**Comment by Marius1311** [comment]
thanks for merging!

**Pull request merged**
